### ISSUE TITLE
Would it scale for a large corpus?

### ISSUE THREAD

**Issue by Sandeep42** [shangjingbo1226/AutoPhrase#1]
Hi,

First of all, thank you for the wonderful open source contribution. One of the things that I could find in the previous SegPhrase implementation was that the frequent pattern mining is not scalable to a large text corpus because of the python implementation. Would this implementation scale to large corpus?

I have a very patchy understanding of C/C++ so I don't quite understand it completely. 

Thank you
Sandeep

**Comment by remenberl** [comment]
Hey Sandeep,

We have several tests about the memory consumption. Based on our observations on relatively large corpus (1GB-4GB), peak memory of AutoPhrase will be roughly around 4X compared with the corpus size. To further lower down the memory requirement, you can try increasing MIN_SUP.

Best,

Jialu
