### ISSUE TITLE
Unable to download DBLP.txt.gz

### ISSUE THREAD

**Issue by yxtay** [shangjingbo1226/AutoPhrase#10]
DBLP.txt.gz seems to have been moved as the URL (http://dmserv2.cs.illinois.edu/data/DBLP.txt.gz) leads to a 404 right now. What is the new URL to get the data?

**Comment by yxtay** [comment]
I noticed that there is a `DBLP.5K.txt` file in `data/EN`. Is that the intended sample file? If so, perhaps changes need to be made to the default run.

**Comment by shangjingbo1226** [comment]
DBLP.5K.txt is a way smaller sample. I will check the dmserv2. Maybe the webserver is down.

**Comment by JohnChinaWu** [comment]
How is it going now? I still have the same issue.

 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /data/DBLP.txt.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Scientific Linux) Server at dmserv2.cs.illinois.edu Port 80</address>
</body></html>

**Comment by Fareedah** [comment]
I have the same issue. Any solution for this problem? Thanks. @shangjingbo1226

**Comment by shangjingbo1226** [comment]
It should work now. Please have a check.

**Comment by JohnChinaWu** [comment]
It works. Thanks 

John Wu

**Comment by yxtay** [comment]
Thanks @shangjingbo1226 !
