### ISSUE TITLE
DOCKER PROBLEM : [pool-1-thread-5] WARN DICLOG - not find library.properties in classpath use it by default ! 

### ISSUE THREAD

**Issue by wangruian153** [shangjingbo1226/AutoPhrase#102]
I download docker and use my own Chinese file to run  ./auto_phrase.sh, but it also gave many warnings and errors like:

[pool-1-thread-5] WARN DICLOG - not find library.properties in classpath use it by default !
[pool-1-thread-5] WARN DICLOG - init userLibrary  warning :/autophrase/library/default.dic because : file not found or failed to read !

I want to know if this problem influence final result and if I must solve it? Thanks very much!

**Comment by remenberl** [comment]
I have pushed a fix and updated docker to add the missing dict files. Please rerun the script.
