### ISSUE TITLE
请问如何运行 WikipediaEntities 来得到entities

### ISSUE THREAD

**Issue by ShawnXiha** [shangjingbo1226/AutoPhrase#11]
已经clone了WikipediaEntities,但是不知道怎么用,他的readme上也没有说.
O(∩_∩)O谢谢

**Comment by shangjingbo1226** [comment]
I'm not quite sure about my memory. But I think you can import their codes into Eclipse and check the pom.xml to install the dependencies. Then, you should be able to run it.

**Comment by ShawnXiha** [comment]
谢谢!

**Comment by QianyangPeng** [comment]
mvn install
mvn exec:java -Dexec.mainClass="cogithub.kno10.wikipediaentities.ParseWikipedia"
