### ISSUE TITLE
After install openjdk-8-jre, no javac avaliable

### ISSUE THREAD

**Issue by lucky6qi** [shangjingbo1226/AutoPhrase#12]
Should be:

Ubuntu:

    g++ 4.8 $ sudo apt-get install g++-4.8
    Java 8 $ sudo apt-get install openjdk-8-jdk
    curl $ sudo apt-get install curl

(Also curl is required)

**Comment by shangjingbo1226** [comment]
Thanks for your useful feedback. I will update the README file soon.
