### ISSUE TITLE
Can you please make some recommendations on memory tuning on a big corpus for Java newbie?

### ISSUE THREAD

**Issue by hcl14** [shangjingbo1226/AutoPhrase#14]
I tried to run on big corpora (4-40 GB, java 1.8, ubuntu) and observed the following behavior:

Tokenizing input file on training phase crashes with `java.lang.OutOfMemoryError: GC overhead limit exceeded`. When I tried to tune java heap size according to the recommendations on Stackoverflow, I added `-Xms20g -Xmx40g -XX:-UseGCOverheadLimit` and then tokenizing still crashes with either the same message of `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`.

The memory usage is always around 10-16 GB, while I have 32 GB RAM and 32 GB swap, so I expected to be able to process up to 16 GB corpus according to the 4x estimation for `MIN_SUP=30`. 

I've tried bigger values of `MIN_SUP` on smaller datasets, but the results seem worse for me.

It seem for me that java settings restrict the memory usage. Could you please give me some help on tuning? 

The dataset I used for testing was 37 GB Gutenberg from [http://www.gutenberg-tar.com/](http://www.gutenberg-tar.com/) which I merged into one big txt file. The maximum size of the file I can tokenize without error is 2 GB. But then `segphrase_train` crashes:

```
segphrase_train: src/classification/../model_training/segmentation.h:504: double Segmentation::adjustPOSTagTransition(std::vector<std::pair<long long int, long long int> >&, int): Assertion `f[i] > -1e80' failed.
./auto_phrase.sh: line 108: 10522 Aborted                 (core dumped) 
```

**Comment by shangjingbo1226** [comment]
During the tokenization, MIN_SUP has no effect.

How many distinct tokens are there in the training corpus? 

Also, if you are running large corpus, please comment out the "// #define LARGE" in the ```parameters.h```

**Comment by hcl14** [comment]
Thanks for the answer @shangjingbo1226 , the numbers of tokens, etc are comparable with the ones in the next issue on POS tags, as here I am using first 2 GB from the same Gutenberg corpus. 
I have `// #define LARGE` uncommented.
I will try to convert everything to ASCII then and tell the results.

**Comment by hcl14** [comment]
@shangjingbo1226 Do you mean that tokenization should work in fixed RAM, i.e. 10-16 GB ? 
If so, why are there java heap errors then?

**Comment by shangjingbo1226** [comment]
Yes, the tokenization should work within the fixed RAM. That java heap error also looks weird to me.
