### ISSUE TITLE
"POS file doesn't have enough POS tags" and no output when training on custom corpus

### ISSUE THREAD

**Issue by hcl14** [shangjingbo1226/AutoPhrase#15]
Hi, I am training on the first 1100MB of Gutenberg [http://www.gutenberg-tar.com/](http://www.gutenberg-tar.com/) and have the following error, and nothing is generated in **results** folder:

```
===Compilation===
===Tokenization===
Current step: Tokenizing input file...
real    2m0.784s
user    10m22.952s
sys     0m17.820s
Detected Language: EN
Current step: Tokenizing wikipedia phrases...
No provided expert labels.
===Part-Of-Speech Tagging===
Current step: Merging...
===AutoPhrasing===
=== Current Settings ===
Iterations = 2
Minimum Support Threshold = 30
Maximum Length Threshold = 6
POS-Tagging Mode Enabled
Number of threads = 10
Labeling Method = DPDN
        Auto labels from knowledge bases
        Max Positive Samples = -1
=======
Loading data...
# of total tokens = 216070506
max word token id = 5117344
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
# of documents = 23194556
# of distinct POS tags = 57                                                                                                                            
Mining frequent phrases...                                                                                                                             
selected MAGIC = 5117347                                                                                                                               
# of frequent phrases = 5420607                                                                                                                        
Extracting features...                                                                                                                                 
Constructing label pools...                                                                                                                            
        The size of the positive pool = 31419                                                                                                          
        The size of the negative pool = 5384346                                                                                                        
# truth patterns = 220417                                                                                                                              
Estimating Phrase Quality...
Segmenting...
Rectifying features...
Estimating Phrase Quality...
Segmenting...
Dumping results...
Done.

real    14m30.644s
user    68m46.148s
sys     4m15.356s
===Saving Model and Results===
===Generating Output===
```

My settings are:

```
#!/bin/bash
MODEL=${MODEL:- "models/DBLP"}
# RAW_TRAIN is the input of AutoPhrase, where each line is a single document.
RAW_TRAIN=${RAW_TRAIN:- data/input.txt}
# When FIRST_RUN is set to 1, AutoPhrase will run all preprocessing. 
# Otherwise, AutoPhrase directly starts from the current preprocessed data in the tmp/ folder.
FIRST_RUN=${FIRST_RUN:- 1}
# When ENABLE_POS_TAGGING is set to 1, AutoPhrase will utilize the POS tagging in the phrase mining. 
# Otherwise, a simple length penalty mode as the same as SegPhrase will be used.
ENABLE_POS_TAGGING=${ENABLE_POS_TAGGING:- 1}
# A hard threshold of raw frequency is specified for frequent phrase mining, which will generate a candidate set.
MIN_SUP=${MIN_SUP:- 30}
# You can also specify how many threads can be used for AutoPhrase
THREAD=${THREAD:- 10}
```

**Comment by shangjingbo1226** [comment]
This is usually caused by some non-ASCII characters in the English input. The POS tagger is borrowed from a third party. I really don't know how to fix this error by modifying the POS tagger. Could you please first try to clean the input? I faced the similar problem before and it was fixed after a simple clean.

**Comment by shangjingbo1226** [comment]
It's also great if you can find some better POS tagger. :)

**Comment by hcl14** [comment]
Thanks @shangjingbo1226 , I will try cleaning the input. 

I may try to attach Stanford NLP as POS tagger, if I figure out how to do it.

**Comment by remenberl** [comment]
Another option is to disable the pos tagger in the script. Not sure if that's acceptable at your side :-)

**Comment by hcl14** [comment]
@remenberl Thanks, but as far as I understood, it will be just statistical search, so perhaps I will spend more effort to know whether POS tagging adds more quality.

**Comment by hcl14** [comment]
@remenberl @shangjingbo1226  Hi, sorry for the late response, I have an update on the situation.

I found that even converting to ASCII
```
iconv -f UTF8 -t ASCII//TRANSLIT source.txt > result.txt
```
lefts intact some control characters like `U+0008` or `U+0014`, which might be a source of crashes. Old tokenizer also preserved them. I decided to change tokenizer and POS tagger and here is my attempt to use Stanford POS tagger:

[https://github.com/hcl14/AutoPhrase](https://github.com/hcl14/AutoPhrase)

I let Stanford tagger to skip all the characters it does not accept and then generate `raw_tokenized` and everything else from its output. It works much longer (2GB corpus is POS tagged in 70 min on 8-core i7), but should me much more precise. I also used bash to create all the necessary files which is very inefficient and involves making a lot of copies of the data (I expect to write Python implementation later).

**Comment by hcl14** [comment]
I have a question about implementation: do line breaks in the data matter for the quality? Because with Stanford POS tagger it's easier to make a text without line breaks (at the moment line break occurs when there is an empty line(s)).

**Comment by hcl14** [comment]
BTW, if about those control characters Stanford NLP is complaining about being untokenizable, they can be filtered with [java function `Character.isIdentifierIgnorable()`](https://stackoverflow.com/a/24707189/1692060). I performed cleaning of `raw_input_tokenized.txt` with it and it seemed to work, but I'm not sure if only that causes problems.

Here is java
[CharFilter.java.txt](https://github.com/shangjingbo1226/AutoPhrase/files/1543697/CharFilter.java.txt)
 code for cleaner:

**Comment by hcl14** [comment]
The quality with Stanford POS tagger is not as good at the moment, but I think filtering above is useful for your current application, at least at the moment I am able to process the corpus which was giving me errors like above or

```
$ bash auto_phrase.sh ~/process_reddit/submissions/RS_2017-11.all_ascii.txt         
===Compilation===
===Tokenization===
Current step: Tokenizing input file...
real    4m12.808s
user    25m26.152s
sys     0m22.524s
Detected Language: EN
Current step: Tokenizing wikipedia phrases...
No provided expert labels.
===Part-Of-Speech Tagging===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3260k  100 3260k    0     0  1635k      0  0:00:01  0:00:01 --:--:-- 1635k
English parameter file (Linux, UTF8) installed.
Current step: Tagging...
ERROR: Empty list of tags in function new_tag_buffer
aborted.
```

**Comment by shangjingbo1226** [comment]
Thanks so much for your feedback. I will definitely dive into this problem soon. Maybe it's the time to develop our own tokenizers and pos taggers T_T.

**Comment by hcl14** [comment]
@shangjingbo1226  Thanks, there are also two things that I want to mention:

You can use the [newer version of tree-tagger](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/) as well, but the problem is that number of distinct POS tags for it is also 45 (the same as for Stanford), and it drops the quality of the result (on my opinion). You current POS tagger has 57 POS tags and the phrases are better.

Here is how cleaning should be made for the texts (I am working with Reddit dumps, so everything can be encountered):

1) You need to clean special characters like U+0008 and U+0014, which are somewhy left intact during conversion to ASCII. This can be done by java CharFilter above.

To avoid "ERROR: Empty list of tags in function new_tag_buffer" and POS tagger crash you need to:
2) Remove long non-character sequences (like "000 001 002 003 ...") - tokenizer is crashing there with the following conversion (here I start from 7 character sequence of non-letters and spaces):
```
sed -E -i 's/(\s*[^a-zA-Z]+\s*){7,}/\1/g' out.txt
```
3) Remove multi-line repeating sequences. I was crashing at the long sequence of the same line:
```
r
r
r
r
```
For this particular case (one repeating line) you one can do:
```
sed '$!N; /^\(.*\)\n\1$/!P; D' test.txt
```

I am working on eliminating other, more complicated cases.

**Comment by shangjingbo1226** [comment]
Thanks for such a detailed suggestion!! I will try to incorporate these in future!
