### ISSUE TITLE
Can't access the DBLP.txt.gz

### ISSUE THREAD

**Issue by abc3436645** [shangjingbo1226/AutoPhrase#19]
Hi jingbo,

I am so excited when I read you paper, but I can't access the  data of DBLP, I also try change my IP proxy, I still can't access the data.

the problems details:
curl http://dmserv2.cs.illinois.edu/data/DBLP.txt.gz --output data/DBLP.txt.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to dmserv2.cs.illinois.edu port 80: Connection refused

after changing the proxy: the data size is 0 byte

I hope that I can get your help soon.

Thanks,
Jianan

**Comment by shangjingbo1226** [comment]
The HTTP service was down before. It should work now.
