### ISSUE TITLE
some files not found, when execute auto_phrase.sh

### ISSUE THREAD

**Issue by CenturySee** [shangjingbo1226/AutoPhrase#2]
when I execute auto_phrase.sh, some Exceptions are founded:
java.io.FileNotFoundException: tmp/final_quality_multi-words.txt
java.io.FileNotFoundException: tmp/final_quality_unigrams.txt
java.io.FileNotFoundException: tmp/final_quality_salient.txt

According to the error information, something wrong was located 
at Tokenizer.tokenizeText(Tokenizer.java:618)
at Tokenizer.main(Tokenizer.java:766)

so, how to resolve this?

**Comment by remenberl** [comment]
May I ask what the language is your data set? Or can you provide a sample set for us to reproduce the results?

**Comment by CenturySee** [comment]
I just use the Default Run as the README writes which will download DBLP.txt.gz from "http://dmserv2.cs.illinois.edu/data/DBLP.txt.gz". Maybe something goes wrong with the downloaded file. I will check it first.

**Comment by remenberl** [comment]
It's quite strange. According to your reported exception, the bash script got stuck at the very end of the job (Generating Output stage, line 108). I have rerun the current repository on our Linux machine but couldn't see this problem. Could you paste the complete log?

**Comment by remenberl** [comment]
The dataset should be correct.
I guess the problem is with your environment. Could you help provide your operating system and java version (run java -version)?

**Comment by remenberl** [comment]
If it is linux, I need your kernel output by running 

> uname -r

**Comment by CenturySee** [comment]
I am using mac os sierra, 
java version is 
**java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)**
the mac os kernel output is **16.3.0**

**Comment by remenberl** [comment]
FYI, I have tested on a notebook with sierra (16.3.0) installed. After installing gcc6 and java8, the script runs correctly. Please consider reinstalling gcc and java following the updated instructions

g++ 6 `$ brew install gcc6`
Java 8 `$ brew update; brew tap caskroom/cask; brew install Caskroom/cask/java`

After installation, you should have the following versions for gcc and java respectively.
gcc version 6.2.0 (Homebrew gcc6 6.2.0)
java version "1.8.0_112"
