### ISSUE TITLE
Buffer Limit Exceeded

### ISSUE THREAD

**Issue by Kyon-N** [shangjingbo1226/AutoPhrase#21]
When I'm trying to apply AutoPhrase on Chinese corpus(with wiki_cn model), it happens.

By my observation, a token A only appears once in the corpus, and when function mappingBackText in AutoPhrase/tools/tokenizer/src/Tokenizer.java loads this token, the text in buffer has already exceeded where the token is. Thus this error happens.

**Comment by shangjingbo1226** [comment]
The segmentation for non-English corpus is not working very well. I will invest more time after the KDD deadline, which is Feb 11.  Thanks!

**Comment by shangjingbo1226** [comment]
Try it now and let me know if it works. You may want to remove all intermediate results first.

**Comment by MouH** [comment]
I am using the latest code, and I met the same error in the last step, "Generating Output", of "phrasal_segmentation.sh".

**Comment by shangjingbo1226** [comment]
Please provide them if possible. You can either post here using some sharable link or send an email to me.

**Comment by MouH** [comment]
I sent you an email, pls check it

**Comment by shangjingbo1226** [comment]
Received, Thanks!

**Comment by mohammadzainabbas** [comment]
@shangjingbo1226 I am having the same issue in the 'Generating Output' step. I have used my own data corpus while still using the pre-trained model.
