### ISSUE TITLE
FileNotFoundException: tmp/raw_tokenized_text_to_seg.txt 

### ISSUE THREAD

**Issue by RubyChou** [shangjingbo1226/AutoPhrase#23]
First, I replaced the DBLP.txt with my corpus and appended some terms in wiki_quality.txt. Then I ran the auto_phrase.sh. Everything went well. Then I chose first 10 lines of the corpus  as a test file and set the TEXT_TO_SEG to the file path. However , when I ran the phrasal_segmentation.sh, it showed a exception as below,

```
===Compilation===
===Tokenization===
[pool-1-thread-3] WARN DICLOG - not find library.properties in classpath use it by default !
[pool-1-thread-3] WARN DICLOG - init userLibrary  warning :/home/zhouyisha/AutoPhrase/library/default.dic because : file not found or failed to read !
[pool-1-thread-3] WARN DICLOG - init ambiguity  error :/home/zhouyisha/AutoPhrase/library/ambiguity.dic because : not find that file or can not found!
[pool-1-thread-2] INFO DICLOG - init core library ok use time :549
[pool-1-thread-4] INFO DICLOG - init ngram ok use time :508

real	0m1.677s
user	0m4.064s
sys	0m0.180s
Detected Language: CN
===Part-Of-Speech Tagging===
===Phrasal Segmentation===
=== Current Settings ===
Segmentation Model Path = models/DBLP/segmentation.model
After the phrasal segmentation, only following phrases will be highlighted with <phrase> and </phrase>
	Q(multi-word phrases) >= 0.500000
	Q(single-word phrases) >= 0.800000
=======
POS guided model loaded.
# of loaded patterns = 1656
# of loaded truth patterns = 3206
POS transition matrix loaded
Phrasal segmentation finished.
   # of total highlighted quality phrases = 11
   # of total processed sentences = 20
   avg highlights per sentence = 0.55

real	0m0.010s
user	0m0.008s
sys	0m0.000s
===Generating Output===
java.io.FileNotFoundException: tmp/raw_tokenized_text_to_seg.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Tokenizer.mappingBackText(Tokenizer.java:595)
	at Tokenizer.main(Tokenizer.java:848)
```

I checked the tmp folder, there wasn't a file named raw_tokenized_text_to_seg.txt indeed. 
Could you help me to find out the reason why this file haven't been generated. And during which process this file will be generated? Thanks a lot.

**Comment by shangjingbo1226** [comment]
Currently, the last step for putting Chinese phrases back to the raw text has some problem.  We are working on this problem now. Please stay tuned.

**Comment by shangjingbo1226** [comment]
Try it now and let me know if it works. You may want to remove all intermediate results first.

**Comment by RubyChou** [comment]
hi @shangjingbo1226 , I tried the new version and the exception seemed disappear. However it took too much time to generate the output even though I just used a piece of text that only contains ten lines. After about 20 minutes, the script didn't stop. So I killed it.  
This time I deleted all files in the project in case any intermediate results left and download the project again. I cannot find the reason why this isn't any output. May the encode matter？ As I find the 'stopwords.txt' in data/CN path has unreadable code like below,
![tmp](https://user-images.githubusercontent.com/19970946/36717555-7b6629fc-1bd9-11e8-899c-a842908fd141.jpg)

**Comment by shangjingbo1226** [comment]
Thanks for your feedback! I will investigate again.

**Comment by QianyangPeng** [comment]
Can you provide your input that causes the bug?

**Comment by RubyChou** [comment]
fine, I've wrote an email to your school email address @shangjingbo1226 and attached a txt file that I used. Please check it. @QianyangPeng  sorry I don't know your email address so maybe you can ask jingbo to share that file to you?

**Comment by shangjingbo1226** [comment]
Thanks for the email. I've shared the file with @QianyangPeng

**Comment by QianyangPeng** [comment]
@RubyChou The bug should have been fixed in the newest Pull Request

**Comment by shangjingbo1226** [comment]
I've merged it. Please have a check.

**Comment by RubyChou** [comment]
Thank you @QianyangPeng  It's been fixed now.  However, when I use a larger corpus, not too big, just 709KB,  it shows, "token = 119
[Fatal Error] Buffer Limit Exceeded! You may want to modify the buffer limit in the Tokenizer.java". Maybe what's in the buffer was wrong tokenized. But I have no idea how to solve it.

**Comment by shangjingbo1226** [comment]
Can you please send me the new corpus?
