### ISSUE TITLE
Different MIN_SUP VALUES RETURN DIFFERENT RESULTS

### ISSUE THREAD

**Issue by siyuan126** [shangjingbo1226/AutoPhrase#24]
Hi, Jingbo! I tried to run the scripts on the same dataset with different min_sup values, and for each value, I get a list of quality phrase and quality single words. Not surprisingly, those lists are different in lengths as well as values. Here is my question, is there a way to evaluate which result is better than another without human annotation involved?  For now, I did a count for each phrase to see how many times it shows up in the documents.

**Comment by shangjingbo1226** [comment]
Hi Siyuan,

Yes, different min_sup will give you different values. It's pretty hard to judge without involving human. You can randomly sample some (e.g., 100) of those quality phrases (e.g., score > 0.5), label them, and get the precision. Also, you may also want to consider the number of quality phrases you can obtain.

Thanks,
Jingbo
