### ISSUE TITLE
Segmentation fault on large corpus

### ISSUE THREAD

**Issue by abc3436645** [shangjingbo1226/AutoPhrase#27]
Hi Jingbo,
   The Segmentation fault occurs when I change the TRAIN_DATA, I have  commented out the // define LARGE in the beginning of src/utils/parameters.h. the train data 's size is 35GB.  the details is below,

of documents = 175912840
of distinct POS tags = 56
Mining frequent phrases...
selected MAGIC = 3746593
./auto_phrase.sh: line 110: 16940 Segmentation fault      (core dumped) ./bin/segphrase_train --pos_tag --thread $THREAD --pos_prune data/BAD_POS_TAGS.txt --label_method $LABEL_METHOD --label $LABEL_FILE --max_positives $MAX_POSITIVES --min_sup $MIN_SUP

Best wishes,

Jianan

**Comment by shangjingbo1226** [comment]
It looks strange to me. Is it possible to share the data with me? Or the information?

**Comment by abc3436645** [comment]
I just use the much larger text dataset,  maybe you can use another dataset, The segmentation fault error will occur again. I think It is not the data problems, and  I also have printed some output information, I will spend more much time on the output information, and I hope you can check this problem, thanks.

I only change the RAW_TRAIN on auto_phrase.sh

RAW_TRAIN=${RAW_TRAIN: - /mnt/data/abstract_origin.txt}

**Comment by JSybrandt** [comment]
I am also getting an issue on this with a "double free or corruption" error

**Comment by shangjingbo1226** [comment]
Okay, I will try a large corpus to see what happen and get back to you as soon as possible.

**Comment by JSybrandt** [comment]
I don't know about the original poster, but I only had this issue when I attempted to turn off the POS tagging.

**Comment by shangjingbo1226** [comment]
I see. This information could be useful. Thanks!

**Comment by abc3436645** [comment]
I have split the large dataset(35G) into 4 pieces(8.8G), each pieces have been tested successfully on AutoPhrase. and I also print more information when I applied AutoPhrase on the large corpus, the "Segmentation fault" occurs on the line of  217-229  of "frequent_pattern_mining.h" (AutoPhrase/src/frequent_pattern_mining/frequent_pattern_mining.h), It may be helpful to you.

**Comment by shangjingbo1226** [comment]
Thanks! I will take a look soon.

**Comment by abc3436645** [comment]
Hi Jingbo:
   we have fixed the segmentation fault,  It due to the Out of bounds of variables。the details is below:
the original code locates the line 157(frequent_pattern_mining.h)

original code:
           inline bool pruneByPOSTag(int st, int ed)

changed:
           inline bool pruneByPOSTag(TOTAL_TOKEN_TYPE st, TOTAL_TOKEN_TYPE ed)

Another problem needs to pay more attention to it, I cost about 90% memory usage on a 128GB machine when we apply the AutoPhrase on 36G data. 

Best wishes,

Jianan Hu

**Comment by shangjingbo1226** [comment]
Thanks for pointing this out! Yeah, the memory consumption is really a problem. I've tried my best to reduce the memory cost. You may also want to increase the MIN_SUP to reduce the number of phrase candidates.
