### ISSUE TITLE
language compatible 

### ISSUE THREAD

**Issue by wrongbattery** [shangjingbo1226/AutoPhrase#3]
" The language in the input will be automatically detected". So there's no way for me to apply your algorithm for my language (Vietnamese). I think you should make the algorithm flexibly by allowing human efforts so that if people make use of this algorithm in clever way and suitable for their language, they will get a big step in processing languages. Thank you.

**Comment by shangjingbo1226** [comment]
Thanks for your interests and suggestion. I've added a way to specify the language in the pre-processing. Please check the new tools/tokenizer and the instructions in the README. Please let me know if you have any further questions or concerns.

**Comment by wrongbattery** [comment]
thanks

**Comment by shangjingbo1226** [comment]
I've also added a brief README about how to generate wiki_all and wiki_quality in new languages. Maybe you will also be interested in.
