### ISSUE TITLE
quality phrase results change every time I run the bash file

### ISSUE THREAD

**Issue by siyuan126** [shangjingbo1226/AutoPhrase#33]
Hi, jingbo!
I ran the bash file on the exactly same input file, with exactly same environment variables (min_sup) several times, I but got different results every time. Could you please let me know why this happened? 

Thank you,
Yuan

**Comment by shangjingbo1226** [comment]
There is some randomness in the classifier. So, yes, the results might be different. My suggestion is that you can save the best model by running it multiple times. And then fix this part before you apply the results to your own applications.
