### ISSUE TITLE
Load Limit Exceeded

### ISSUE THREAD

**Issue by pruales** [shangjingbo1226/AutoPhrase#35]
I am running Autophrase on a 1.66 GB corpus and during phrasal segmentation I got this error. I'm not sure if I should cut down the size of the corpus or try something else. What is causing this error?

**Comment by remenberl** [comment]
To run a Autophrase with 1.66G corpus, a machine should better have 8GB memory. If there is only 4GB available, try cutting the corpus to 1GB.
