### ISSUE TITLE
phrase segmentation problem with phrasal_segmentation.sh

### ISSUE THREAD

**Issue by twjiang** [shangjingbo1226/AutoPhrase#38]
In the phrasal_segmentation.sh, the default setting is:
HIGHLIGHT_MULTI=${HIGHLIGHT_MULTI:- 0.5}
HIGHLIGHT_SINGLE=${HIGHLIGHT_SINGLE:- 0.8}
to segment the quality phrases.

I use the phrasal_segmentation.sh to segment my own corpus, before that I have got the segmentation.model under the same corpus.

However, the final segmentation.txt I got has many low quality single-word as phrase:
e.g.
The <phrase>paper</phrase> describes a <phrase>natural language</phrase> based expert system route advisor for the <phrase>public</phrase> <phrase>bus</phrase> <phrase>transport</phrase> in <phrase>Trondheim</phrase>, <phrase>Norway</phrase>. 

even the quality of these single word is much lower than 0.8:
0.4528807447	paper
0.5108750335	public
0.5367821510	bus
...

**Comment by shangjingbo1226** [comment]
Are these phrases in the wiki_quality.txt list? If so, this is the reason. I intended to include all high-quality phrases from wiki_quality.txt.
