### ISSUE TITLE
AutoPhrase in Python

### ISSUE THREAD

**Issue by alfords** [shangjingbo1226/AutoPhrase#39]
I find the AutoPhrase is working well on text mining i.e. topic modeling. May I know if there is a AutoPhrase package in Python? Thank you.

**Comment by shangjingbo1226** [comment]
I'm glad that you find AutoPhrase useful in topic modeling. We have a plan to make it as a Python package. Currently, it can only consume the segmentation models and apply it to new texts. 

I will update the README once it's ready for the general usages.
