### ISSUE TITLE
Can I custom AutoPhrase for Vietnamese by modifying stopwords.txt, and wiki files

### ISSUE THREAD

**Issue by tuananhhedspibk** [shangjingbo1226/AutoPhrase#4]

**Comment by shangjingbo1226** [comment]
Yes, I think you can but you may also modify the tokenizer. Please find the instructions in the README.

**Comment by tuananhhedspibk** [comment]
ok, thanks you very much

**Comment by tuananhhedspibk** [comment]
Sorry, but can you tell me about "workflow" of this "Autophrase", thanks you guy :)

**Comment by shangjingbo1226** [comment]
You can refer to the auto_phrase.sh.

In the very beginning, we run tokenizer to process the raw input to token-id style input. After this, the following steps are exactly same for any language. In the end, we will use the tokenizer again to translate the token-id back to its surface language.
