### ISSUE TITLE
not enough training data found!

### ISSUE THREAD

**Issue by xuxiaoxiaoLord** [shangjingbo1226/AutoPhrase#40]
not enough training data found!
hello,I have a question.when I try to use my own input.txt always occur this error.
would you like to tell  me the reason? 
thank you so much!

**Comment by shangjingbo1226** [comment]
It's likely either you have a too small input corpus or a too high MIN_SUP threshold. In any of these cases, the number of candidate phrases becomes 0 and the classifier will report such error.
