### ISSUE TITLE
wiki_all.txt and wiki_quality.tx

### ISSUE THREAD

**Issue by zulema36** [shangjingbo1226/AutoPhrase#41]
you could publish the files wiki_all.txt and wiki_quality.txt in Portuguese? 
using wikipedia ptwiki the files were generated: links, linktext y redirects.gz
using the wikidata-20180720-all.json.bz2, the file was generated by redirecting the output of this phase (load-wikidta) to a file wikidata.tsv.gz.
but unfortunately analyse-links generates an entities.gz file but empty. Can you explain what is happening? We want to use your method in a Portuguese base

**Comment by shangjingbo1226** [comment]
I'm not quite sure about this issue. You may want to ask the author of [WikipediaEntities](https://github.com/kno10/WikipediaEntities).
