### ISSUE TITLE
[Fatal Error] Load Limit Exceeded! You may want to modify the load limit in the Tokenizer.java

### ISSUE THREAD

**Issue by xiaonanzzz** [shangjingbo1226/AutoPhrase#42]
I got this error when I run the phrase_segmentation.sh on a huge txt file (990K lines, 68MB).
I cannot provide the file for reproducing the problem because this data is not public. 
I got some partial output in Semengtation.txt
So my best guess is that the file is too large? 

Please let me know if there is any easy to to solve this issue.

**Comment by shangjingbo1226** [comment]
You can modify the Java code to enlarge the Load Limit. Or, you can apply a simple filter to your corpus to remove redundant whitespaces and those special characters. These are the major reasons to cause such an error.

**Comment by xiaonanzzz** [comment]
> You can modify the Java code to enlarge the Load Limit. Or, you can apply a simple filter to your corpus to remove redundant whitespaces and those special characters. These are the major reasons to cause such an error.

Thanks a lot for your response!
I modified the load limit in java code. But the error still exists. I found that it doesn't happen at tokenization step. It happens at the step of generating output.
Here is the console output.
```
===Compilation===
===Tokenization===
Current step: Tokenizing input file...
real	0m13.932s
user	0m28.348s
sys	0m2.068s
Detected Language: EN
===Part-Of-Speech Tagging===
Current step: Merging...
===Phrasal Segmentation===
=== Current Settings ===
Segmentation Model Path = models/dress-title-min1k/segmentation.model
After the phrasal segmentation, only following phrases will be highlighted with <phrase> and </phrase>
	Q(multi-word phrases) >= 0.500000
	Q(single-word phrases) >= 0.800000
=======
POS guided model loaded.
# of loaded patterns = 1723
# of loaded truth patterns = 99185
POS transition matrix loaded
Phrasal segmentation finished.
   # of total highlighted quality phrases = 3630772
   # of total processed sentences = 1060754
   avg highlights per sentence = 3.42282

real	0m38.005s
user	0m31.793s
sys	0m1.340s
===Generating Output===
[Fatal Error] Load Limit Exceeded! You may want to modify the load limit in the Tokenizer.java
```

**Comment by shangjingbo1226** [comment]
If the limit has been increased to a very big number, please think about cleaning your input data.
