### ISSUE TITLE
[ERROR] not enough training data found!

### ISSUE THREAD

**Issue by JackySnake** [shangjingbo1226/AutoPhrase#43]
Hi，when in use ‘autophrase’ to process my corpus. It tell me "[ERROR] not enough training data found!" and can not generate any result.
My corpus is ancient Chinese. And I have merge my domain entity mention into the ‘wiki_quality.txt’ and these mention  definitely occurrence in the corpus many times.  I wonder if you could help me with this.
Thanks you very much.
The shell output：
=== Current Settings ===
Iterations = 2
Minimum Support Threshold = 10
Maximum Length Threshold = 6
POS-Tagging Mode Enabled
Number of threads = 10
Labeling Method = DPDN
	Auto labels from knowledge bases
	Max Positive Samples = -1
=======
Loading data...
# of total tokens = 0
max word token id = 0
# of documents = 0
# of distinct POS tags = 0
Mining frequent phrases...
selected MAGIC = 1
# of frequent phrases = 1
Extracting features...
Constructing label pools...
	The size of the positive pool = 0
	The size of the negative pool = 0
# truth patterns = 0
Estimating Phrase Quality...
0 0
[ERROR] not enough training data found!
[ERROR] no training data found!
Segmenting...
Rectifying features...
Estimating Phrase Quality...
0 0
[ERROR] not enough training data found!
[ERROR] no training data found!
Segmenting...
Dumping results...
Done.

**Comment by JackySnake** [comment]
Well...I'm sorry about the format...

**Comment by shangjingbo1226** [comment]
Not really. When you find "not enough training data", it usually means there is no overlap between the frequent n-grams and the given knowledge base (wiki_quality.txt).

According to your output, 
```
# of total tokens = 0
max word token id = 0
```
It seems to me the input corpus is empty. Maybe you specified a wrong input filename?

**Comment by shangjingbo1226** [comment]
I see. If your documents usually have a similar number of sentences, I think this will not affect the results significantly. It depends on how do you reorganize your corpus.
