### ISSUE TITLE
POS file doesn't have enough POS tags

### ISSUE THREAD

**Issue by sylv01** [shangjingbo1226/AutoPhrase#46]
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

openjdk version "1.8.0_181"

When I run `./auto_phrase.sh` on a freshly cloned repository of AutoPhrase I get the error `POS file doesn't have enough POS tags` many hundreds if not thousands of times.  I also get the error `ERROR: not a parameter file: ./lib/english-utf8.par!` at the Part-Of-Speech Tagging step. This doesn't seem like normal behavior as I have used AutoPhrase on a another system and did not get this error.

**Comment by ss87021456** [comment]
I've encountered the same problem too.
my version is listed here:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10)
openjdk version "1.8.0_181"

**Comment by shangjingbo1226** [comment]
The error looks interesting. Is it caused by different Perl versions? We are using the TreeTagger as the POS tagger for English.

**Comment by CN-AlbertWu96** [comment]
The same problem here.
My perl5 version is (revision 5 version 18 subversion 2).
How can we fix it?

**Comment by sylv01** [comment]
My perl version: perl 5, version 16, subversion 3 (v5.16.3)

What is the recommended version of Perl to run?

**Comment by yanhongfirst** [comment]
Got same error. The root cause is the links in tools/treetagger/download_parameter_files.sh are invalid. Only for english, download http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english.par.gz, unzip and mv to tools/treetagger/lib/english-utf8.par.

**Comment by CaoJonas** [comment]
@yanhongfirst thanks for your advice. But the promotion of result shows that _Pos-Tagging Mode Disabled._ There is no change after uncompressing.

**Comment by PxYu** [comment]
> @yanhongfirst thanks for your advice. But the promotion of result shows that _Pos-Tagging Mode Disabled._ There is no change after uncompressing.

Just tried @yanghongfirst solution and it worked. You need to rename the uncompressed file to "english-utf8.par" and (probably) change the file permission to 755.

**Comment by shangjingbo1226** [comment]
I have made this change in the repo. It should work now. Thank you all for the discussion and solution!

**Comment by sylv01** [comment]
> Got same error. The root cause is the links in tools/treetagger/download_parameter_files.sh are invalid. Only for english, download http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english.par.gz, unzip and mv to tools/treetagger/lib/english-utf8.par.

@yanhongfirst This is what fixed it for me and I'm the OP.  Thanks for figuring it out.

**Comment by caolingyu** [comment]
@shangjingbo1226 Hi, it would be better if you could update the docker image as well in order to avoid confusion. Thanks!

**Comment by Yevgnen** [comment]
@yanhongfirst I got the file downloaded and renamed and been chmod successfully automatically. However, there is still thousands of `POS file doesn't have enough POS tags`.

**Comment by remenberl** [comment]
We will investigate the problem brought by POS tagging. One way to work around as a quick solution is to set ENABLE_POS_TAGGING as 0 in the script.
