### ISSUE TITLE
lack of 

### ISSUE THREAD

**Issue by CaoJonas** [shangjingbo1226/AutoPhrase#48]
The lack of parameter file _english.utf8.par_
        Some parameter file can't be downloaded automatically due to invalid URL. I try to download _english.par_  and replace  _english.utf8.par_  with it. but it doesn't work. I am appreciated if I get this parameter file from you.

**Comment by shangjingbo1226** [comment]
Interesting. Is there any change on the TreeTagger side? I will probably investigate this more over this weekend.

**Comment by CaoJonas** [comment]
Thank for your reply. These links from a script are invalidated. It's helpful to replace _english.par_ to _english.utf8.par_ with default corpus, but it doesn't work when I run codes with a part of default corpus.

**Comment by CaoJonas** [comment]
Hi, @shangjingbo1226, I met a new problem POS-Tagging Mode Disabled. I printed the main functionn's parameters, but no extra reminder. Have you been in this situation?

**Comment by CaoJonas** [comment]
Hi, @shangjingbo1226, I met a new problem _POS-Tagging Mode Disabled._ I printed the main functionn's parameters, but no extra reminder. Have you been in this situation?

**Comment by shangjingbo1226** [comment]
Did you change "ENABLE_POS_TAGGING=${ENABLE_POS_TAGGING:- 1}" in the `auto_phrase.sh`?

**Comment by CaoJonas** [comment]
Yeah, I forget to make a difference with the changed script. I got a reasonable result like an example referenced paper showed. Thanks for your help.

**Comment by shangjingbo1226** [comment]
Cool, I'm glad to hear that!
