### ISSUE TITLE
Hi, i have an input file that have doc_id, doc_content, so how can i write output with format: "doc_id" "ranking" "phrase", Thanks you bro

### ISSUE THREAD

**Issue by tuananhhedspibk** [shangjingbo1226/AutoPhrase#5]

**Comment by shangjingbo1226** [comment]
You may do some pre-processing and post-processing by yourself. First, turn the doc_content into the raw text form. Then, run AutoPhrase. In the end, load the segmented text and the phrase ranking list, as well as your original input, print everything you want.
