### ISSUE TITLE
[Fatal Error]: Buffer Limit Exceeded Error! You may want to modify the buffer limit in the Tokenizer.java

### ISSUE THREAD

**Issue by mohammadzainabbas** [shangjingbo1226/AutoPhrase#50]
This issue occurred when I ran `./phrasal_segmentation.sh` and at `Generating Output` stage. 

![image](https://user-images.githubusercontent.com/19189095/49203393-eaea4d80-f3c9-11e8-9e37-19f209f1cb0d.png)

I have used my **own data corpus** (_of size 22 MB_), while still using the _pre-trained model_. (As mentioned in Issue #22, I have changed the `text_to_seg` in the `phrasal_segmentation.sh` script.)

I have tried to increase the Buffer limit from 8192 `default size` to 16384 (`2 x 8192`), 32768 (`4 x 8192`), 65536 (`8 x 8192`), 131072 (`16 x 8192`), 262144 (`32 x 8192`) but no use.

How may I resolve this issue ?

**Comment by mohammadzainabbas** [comment]
I have increased the buffer size to 8388608 (`1024 x default size`), recompiled and left the script running, and it is still running after more than 17 hrs.

![image](https://user-images.githubusercontent.com/19189095/49273560-39b1e900-f497-11e8-9525-b9c14c44411e.png)

**Comment by shangjingbo1226** [comment]
Do you have any special characters in your corpus?

**Comment by mohammadzainabbas** [comment]
Yes, there are special characters.

**Comment by yanhongfirst** [comment]
For me similar problem is caused by emoji in the data which lucene tokenizer break one emoji into two token and skipped by 

https://github.com/shangjingbo1226/AutoPhrase/blob/1de1526d5b0fb463a161b5321b71a78b181377a2/tools/tokenizer/src/Tokenizer.java#L629

                            if (punctuation_mapping.containsKey(token)) {
                                // skip it
                                continue;
                            }

My fix is change to this
             if (punctuation_mapping.containsKey(token)) {
                // skip it
                if (!tokenID.equals(parts[i])) {
                  continue;
                }
                System.out.printf("token %s, tokenID %s, buffer %s\n",
                                  token, tokenID, buffer);
                break;
              }

**Comment by shangjingbo1226** [comment]
I see. I will try to think about how to avoid those special cases carefully. If you have any suggestions, please let me know. Texts are always noisy and unexpected :).

**Comment by mohammadzainabbas** [comment]
@yanhongfirst I have tried your fix on my corpus, but no use, getting the same issue.
@shangjingbo1226 I have tried removing all special characters too with `re.sub('[^A-Za-z0-9]+', ' ', mystring)` as mentioned [here](https://stackoverflow.com/a/5843547/6390175), and ran it again. But no use.

**Comment by shangjingbo1226** [comment]
@mohammadzainabbas you may want to also do something like ' '.join(s.split()) to eliminate too many consecutive whitespaces.

**Comment by LauraBowenHe** [comment]
I have the same issue as @mohammadzainabbas .
But instead of running a big file, I tried a small file, which is the first ten lines of the default text file './data/EN/DBLP.5K.txt'.
And I also set the buffer size as 2048.
However, after 2h, the script was still running. @shangjingbo1226  Can you help me with this?
A lot of thanks!

**Comment by shangjingbo1226** [comment]
@LauraBowenHe are you following the sample bash scripts? Did you make any modification? So you first run `auto_phrase.sh` and then `phrasal_segmentation.sh`?

**Comment by shangjingbo1226** [comment]
I think the error is caused by the previous pull request for Chinese corpus. I have fixed it. It should work for English now. Thanks for raising the issue!

When you are trying again, please first run `rm -rf tools/tokenizer/build` to clear previously built tokenizer java class.
