### ISSUE TITLE
can support partly EN?

### ISSUE THREAD

**Issue by phiedulxp** [shangjingbo1226/AutoPhrase#51]
like positive:
add negative_quality.txt and negative_all.txt

**Comment by shangjingbo1226** [comment]
Could you please elaborate more on these two files? Negative labels are now sampled from the frequent, but not known phrase candidates.

**Comment by phiedulxp** [comment]
negative_all.txt: the raw noise negative pool,
negative_quality.txt: the stop phrases or bad pos pattern

**Comment by shangjingbo1226** [comment]
hmm, in this case, the model will only sample negative instances from `negative_quality.txt`?
