### ISSUE TITLE
Raw input format

### ISSUE THREAD

**Issue by nurlano** [shangjingbo1226/AutoPhrase#52]
What's the correct format for the raw input format?

in the documentation it says, each line should be one document. But DBLP.txt contains one document and a '.'???

here is example DBLP.txt content:

> My Cat Is Object-Oriented.
> .
> Making Database Systems Fast Enough for CAD Applications.
> .
> Optimizing Smalltalk Message Performance.
> .

**Comment by shangjingbo1226** [comment]
The single dot means the abstract is empty.

We expect that each line in the raw input is a document/paragraph.

**Comment by nurlano** [comment]
Got it, thanks
