### ISSUE TITLE
Label back strategy

### ISSUE THREAD

**Issue by XiaChaoStudio** [shangjingbo1226/AutoPhrase#53]
What is the strategy for the rebate part of AutoPhrase? Because we found that there are errors in running the label back program for some corpora, we have solved the problem of letter case, but still feel that the effect of the result is not good enough.

**Comment by shangjingbo1226** [comment]
The label back follows the generative process mentioned in the paper. We use a dynamic programming algorithm to find the best explanation. You may want to set higher thresholds to improve the precision.
