### ISSUE TITLE
请问如何运行WikipediaEntities来解析最新的pages-articles.xml.bz2得到entities？

### ISSUE THREAD

**Issue by Shawn1993** [shangjingbo1226/AutoPhrase#54]
由于WikipediaEntities没有运行指南，大概看了WikipediaEntities的源码，其过程应该是：
1. 编译
2. 运行ParseWikipedia，输出links.gz, linktext.gz, redirects.gz
3. 运行AnalyzeLinks, 输出entities.gz

但是第3步需要一个叫wikidata.tsv.gz的文件，请问这个文件从哪里来？

**Comment by remenberl** [comment]
1. Download "latest-all.json.bz2" from
https://dumps.wikimedia.org/wikidatawiki/entities/.
2. Run LoadWikiData.java
<https://github.com/kno10/WikipediaEntities/blob/062254c06d301c70e04c7e14a40b1cc084664b4a/src/main/java/com/github/kno10/wikipediaentities/LoadWikiData.java>
and
dump print into a file.

That file will be wikidata.tsv.gz after runing gzip command.

**Comment by Shawn1993** [comment]
Thank you so much!
