### ISSUE TITLE
The data used in paper

### ISSUE THREAD

**Issue by Shawn1993** [shangjingbo1226/AutoPhrase#55]
Hi,
This is a great job! I have read the paper and tried a lot with this code. I focus on Chinese corpus. I have some question about data as follow:
1. Is the data of "wiki_quality.txt" and "wiki_all.txt"  in Chinese same as the one used in the paper? If not the same, could you offer or publish the wiki phrase used in the paper?
2. Could you offer or publish the training data of Chinese wiki article? 
3. If you can't provide the data mentioned above, could you offer the  data size of "wiki_quality.txt", "wiki_all.txt" , and Chinese training data?

**Comment by Shawn1993** [comment]
I want to get a good performance, but I got too many stop words when running phrase_segmentation.sh.

**Comment by shangjingbo1226** [comment]
1. The `wiki_quality.txt` and `wiki_all.txt` are the same as we used in the experiments.
2. We use the whole Wiki-ZH dump at that time, with a little preprocessing to clean the raw text.
3. The size of the training data is mentioned in the paper.
4. When you run `phrasal_segmentation.sh`, you may want to first look at the phrase ranked lists and choose appropriate thresholds (especially for unigrams). Higher thresholds will give you more clean results.
