### ISSUE TITLE
running on Bash or sh

### ISSUE THREAD

**Issue by a2975667** [shangjingbo1226/AutoPhrase#56]
It seems that there are some issues (shown below) when running `./phrasal_segmentation.sh` on WSL (windows subsystem ubuntu 18.08). 
```
===Part-Of-Speech Tagging===
./phrasal_segmentation.sh: 44: [: EN: unexpected operator
```

Based on [this](https://stackoverflow.com/questions/3411048/unexpected-operator-in-shell-programming) post, it seems like either running `bash ./phrasal_segmentation.sh` solves the problem or substituting `==` with `=` in the `./phrasal_segmentation.sh` file.

**Comment by shangjingbo1226** [comment]
I see. Thanks for pointing this out!

**Comment by Yevgnen** [comment]
I got a similar error 

```
auto_phrase.sh: 93: auto_phrase.sh: [[: not found
-ne No provided expert labels.

auto_phrase.sh: 100: [: ==: unexpected operator
```

**Comment by a2975667** [comment]
@Yevgnen have you tried to change the == into = in the script?
I think that's how I got mine working.

**Comment by Yevgnen** [comment]
Thanks, that helps. Now I got

```
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
POS file doesn't have enough POS tags
```

as stated in #46 and #66...
