### ISSUE TITLE
Usage of trained model on new corpus

### ISSUE THREAD

**Issue by djstrong** [shangjingbo1226/AutoPhrase#58]
I have trained a model on Wikipedia. I have segmentation.model and list of extracted phrases. How to apply this model to a new corpus to extract new phrases? Is it possible? Or `phrasal_segmentation.sh` only highlights phrases extracted from original corpus?

**Comment by shangjingbo1226** [comment]
You can directly apply the model to the new corpus, however, it can only highlight the phrases that the model has seen in the Wikipedia corpus.
