### ISSUE TITLE
Will larger corpus lead to better phrase quality?

### ISSUE THREAD

**Issue by 1049451037** [shangjingbo1226/AutoPhrase#59]
I notice that the training data ```DBLP.txt``` only contains about 3 million titles. I want to train AutoPhrase with billions of titles and abstract. However, when it trained over, segmentation seems not working very well. Some trivial words such as *experiment result* are labeled as phrases. Are there any points I am missing?

**Comment by shangjingbo1226** [comment]
When you have a larger corpus, you may want to increase the MIN_SUP.
