### ISSUE TITLE
Mining chinese corpus, but all the good new phrases genrated are from the dict

### ISSUE THREAD

**Issue by michael-wzhu** [shangjingbo1226/AutoPhrase#61]
Hi. I was trying out your code to mine new phrases in Chinese. However, i notice that:

1) there is no training steps occured, and it directly generate results;

2) most of the phrases generated are actually in the original dictionary i provided. 

Could you help me to resolve this issue?

**Comment by shangjingbo1226** [comment]
What's the size of your training corpus? What do you mean by "no training steps occurred"? Could you please share the commands that you have run as well as the corresponding screen outputs? Thanks!

**Comment by crystal0913** [comment]
@shangjingbo1226 In Chinese， what statistical features are used to initialize phrase quality
estimator Q？

**Comment by remenberl** [comment]
Please check Section 4.2 in this paper http://hanj.cs.illinois.edu/pdf/sigmod15_jliu.pdf
