### ISSUE TITLE
ERROR: not a parameter file: ./lib/english-utf8.par!

### ISSUE THREAD

**Issue by charmingLiao** [shangjingbo1226/AutoPhrase#64]
**when i run the docker, an error happened as the title said. the whole log as followed:**

> # ./auto_phrase.sh
> ===Compilation===
> ===Tokenization===
> Current step: Tokenizing input file...
> real    0m0.468s
> user    0m0.770s
> sys     0m0.020s
> Detected Language: EN
> Current step: Tokenizing wikipedia phrases...
> ===Part-Of-Speech Tagging===
> Current step: Tagging...
> ERROR: not a parameter file: ./lib/english-utf8.par!
> Current step: Merging...
> ===AutoPhrasing===
> Loading data...
> # of total tokens = 123
> max word token id = 70
> POS file doesn't have enough POS tags

> real    0m0.034s
> user    0m0.010s
> sys     0m0.020s

> ===Generating` `Output===

**and the files under the results directory  are all empty. pls help me !**

**Comment by MTKnife** [comment]
Do you get the "POS file doesn't have enough POS tags" just once, or over and over?

**Comment by remenberl** [comment]
Docker image is updated. Please try it again.
