### ISSUE TITLE
Tokenizer Crash during Phrasal Segmentation

### ISSUE THREAD

**Issue by MTKnife** [shangjingbo1226/AutoPhrase#70]
When I try to run `phrasal_segmentation.sh` with my real data, I get a "load limit" error.

Looking at the text I'm using (and observing, in "segmentation.txt", where things went wrong), the problem appears to be that he segmentation method in `Tokenizer.java` chokes on non-standard characters.  For example, in one case, it's an emoji.  My guess is the fault is occurring in line 642, which can't handle the character in question, and leads to a runaway condition that's broken by the "load limit" check.

**Comment by shangjingbo1226** [comment]
You can increase the load limit in that Java code. Very special characters could be one reason. Another reason could be too many whitespaces in a row. Some necessary pre-processing is strongly recommended.

**Comment by MTKnife** [comment]
Increasing the load limit doesn't actually solve the problem when you're dealing with special characters  I realize that the intent of the code is to skip over bad tokens, and, if all else fails, just give up if you hit a sentence with two many of them.

However, when it comes to special characters, the code doesn't simple skip over the special characters:  something goes completely haywire, and it skips over the subsequent tokens as well, even skipping through subsequent _sentences_ if the load limit is high enough.  Sometimes, it recovers somehow--after skipping a bunch of text that doesn't get tagged.  Sometimes, it never recovers, even with a very high load limit.

At the very least, your error message should probably suggest that increasing the load limit won't solve the problem in the case of special characters.
