### ISSUE TITLE
cannot find library.properities in classpath use it by default

### ISSUE THREAD

**Issue by 270431727** [shangjingbo1226/AutoPhrase#75]
After changing the corpus and running docker to get new model, it shows some errors at the tokenization step as follow:

[pool-1-thread-8] WARN DICLOG - not find library.properties in classpath use it by default !
[pool-1-thread-8] WARN DICLOG - init userLibrary  warning :/autophrase/library/default.dic because : file not found or failed to read !
[pool-1-thread-8] WARN DICLOG - init ambiguity  error :/autophrase/library/ambiguity.dic because : not find that file or can not found!

Though the docker could be completed with such errors, it doesn't give out any output into model file as expected.

**Comment by xtlv426** [comment]
I have the same  issue.

**Comment by remenberl** [comment]
Could you try it again with the new docker image?
