### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by TranNDC** [shangjingbo1226/AutoPhrase#76]
The original paper says:

> For a list of phrases, _precision_ is defined as the number of true quality phrases divided by the number of predicted quality phrases; _recall_ is defined as the number of true quality phrases divided by the total number of quality phrased. - **5.3 Experimental Settings - Evaluation Metrics**

"_Quality phrase_" has already mentioned in Its previous paragraph about Human Annotation. How about **True Quality phrase**? Can you explain more about **True Quality Phrase**?

Many thanks.

**Comment by remenberl** [comment]
Here `true quality phrases` refers to quality phrases based on human annotation. The word `true` is used to compare with the `predicted`. Sorry for the confuse.
