### ISSUE TITLE
default.dic, ambiguity.dic not found error

### ISSUE THREAD

**Issue by MingleiLI** [shangjingbo1226/AutoPhrase#84]
init userLibrary  warning : AutoPhrase/library/default.dic because : file not found or failed to read !
init ambiguity  error : AutoPhrase/library/ambiguity.dic because : not find that file or can not found!

**Comment by aaronlyt** [comment]
I have same, "not find library.properties in classpath use it by default", will some advice, using g++5.3

**Comment by remenberl** [comment]
Fixed by adding the files.
