### ISSUE TITLE
Why does AutoPhrase segmentation include stopwords as phrases?

### ISSUE THREAD

**Issue by napsternxg** [shangjingbo1226/AutoPhrase#9]
I tried running AutoPhrase on a dataset of mine followed by phrasal segmentation. I used my own expert labels file and for the phrasal segmentation set MULTIWORD cutoff at 0.7 and SINGLEWORD cutoff at 0.8, but I ended up getting phrases like the following in my results. 

```xml
We aimed to test <phrase>the</phrase> overexpansion of <phrase>the</phrase> <phrase>BVS</phrase> scaffold in vitro and evaluate the impact of <phrase>excessive</phrase> <phrase>scaffol
d</phrase> <phrase>oversizing</phrase> <phrase>on</phrase> <phrase>focal point</phrase> support
```

In the above example phrases such as `the` and `on` should not be included as they are in conflict with the SegPhrase rule that a phrase should be filtered out if it ends with a stopword. I didn't edit the stopword file, so this behavior is strange.

**Comment by shangjingbo1226** [comment]
Yeah, the current unigram phrase estimation is not as good as multi-word phrases. Please set a higher threshold for the SINGLEWORD.

**Comment by napsternxg** [comment]
Thanks a lot.
