### ISSUE TITLE
Could not find or load main class Tokenizer

### ISSUE THREAD

**Issue by benzom** [shangjingbo1226/AutoPhrase#91]
Trying to launch AutoPhrase for the first time with auto_phrase.sh script, but getting error "Could not find or load main class Tokenizer". I'm using macOS Big Sur 11.5.2. 

I assume the problem should be in java and its installation (I tried to follow guide from readme). Command "brew tap caskroom/cask" is giving error as caskroom/cask was moved, so I tapped homebrew/cask instead

**Comment by renmengjie7** [comment]
I also meet the same problem. How did you solve it?

**Comment by benzom** [comment]
sorry, i don't remember
moreover, I'm not sure if we solved it or just excluded from research

**Comment by remenberl** [comment]
Do you mind trying the docker approach?
